import type {
  DiagnosticSeverity,
  DoctorRuleDefinition,
  SourceBlockKind
} from '@vue-doctor/core'

interface ParseFailureOrder {
  template?: number
  script?: number
}

interface VueRuleRecord extends Omit<
  DoctorRuleDefinition,
  'description' | 'verification' | 'requires' | 'help'
> {
  problem: string
  remediation: string
  sourceBlocks?: SourceBlockKind[]
  allSourceBlocks?: SourceBlockKind[]
  vueVersion?: 'known'
  parseFailureOrder?: ParseFailureOrder
  contextualSeverity?: boolean
}

interface InternalVueRuleDefinition extends DoctorRuleDefinition {
  parseFailureOrder?: ParseFailureOrder
  contextualSeverity?: boolean
}

function defineVueRule(record: VueRuleRecord): InternalVueRuleDefinition {
  const {
    problem,
    remediation,
    sourceBlocks: declaredSourceBlocks,
    allSourceBlocks,
    vueVersion,
    parseFailureOrder,
    ...definition
  } = record
  const sourceBlocks: SourceBlockKind[] = declaredSourceBlocks ? [...declaredSourceBlocks] : []
  if (!declaredSourceBlocks) {
    if (parseFailureOrder?.template !== undefined) sourceBlocks.push('template')
    if (parseFailureOrder?.script !== undefined) sourceBlocks.push('script', 'script-setup')
  }

  return {
    ...definition,
    domain: record.domain ?? 'vue',
    tags: record.tags ?? vueRuleTags(record.code),
    description: problem,
    verification: 'static',
    requires: {
      sourceBlocks: [...new Set(sourceBlocks)],
      ...(allSourceBlocks ? { allSourceBlocks: [...new Set(allSourceBlocks)] } : {}),
      ...(vueVersion ? { vueVersion } : {})
    },
    help: { problem, remediation },
    ...(parseFailureOrder ? { parseFailureOrder } : {})
  }
}

function vueRuleTags(code: string): string[] {
  const tags = ['vue']
  if (/watch|ref|reactive|computed|props-destructure/.test(code)) tags.push('reactivity')
  if (/watch/.test(code)) tags.push('watcher')
  if (/template|v-for|v-if|v-html/.test(code)) tags.push('template')
  if (/emit|model|event/.test(code)) tags.push('interaction')
  if (/app-|global|plugin|provide|inject/.test(code)) tags.push('application')
  if (/prefer-/.test(code)) tags.push('suggestion')
  if (code.startsWith('vue2-')) tags.push('vue2')
  return tags
}

const internalVueRuleDefinitions = [
  defineVueRule({
    code: 'vue-security-restrict-v-html',
    title: 'Restrict v-html to trusted HTML',
    problem: 'v-html can execute untrusted markup and bypasses Vue escaping.',
    remediation: 'Remove v-html or sanitize the HTML before rendering it.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 0 },
  }),
  defineVueRule({
    code: 'vue-template-v-if-for',
    title: 'v-if and v-for share an element',
    problem: 'Combining v-if and v-for makes filtering order-dependent and obscures intent.',
    remediation: 'Move the condition to a wrapper or derive a filtered collection with computed().',
    defaultEnabled: false,
    defaultSeverity: 'warning',
    parseFailureOrder: { template: 3 },
  }),
  defineVueRule({
    code: 'vue-template-v-for-key',
    title: 'v-for is missing a stable key',
    problem: 'Without a stable key Vue cannot reliably preserve item identity during updates.',
    remediation: 'Add a stable primitive :key such as item.id.',
    defaultEnabled: false,
    defaultSeverity: 'warning',
    parseFailureOrder: { template: 1 },
  }),
  defineVueRule({
    code: 'vue-template-shadow',
    title: 'Template scope shadows a script binding',
    problem: 'A v-for alias reuses a script binding name, making template scope ambiguous.',
    remediation: 'Rename the v-for alias or the outer binding so template scope remains explicit.',
    sourceBlocks: ['script', 'script-setup'],
    allSourceBlocks: ['template'],
    defaultEnabled: false,
    defaultSeverity: 'warning',
    parseFailureOrder: { template: 4, script: 28 },
  }),
  defineVueRule({
    code: 'vue-prop-mutated',
    title: 'Vue prop is mutated directly',
    problem: 'Props are read-only inputs and direct mutation breaks one-way data flow.',
    remediation: 'Treat props as read-only and emit an update event or use local state.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 0 },
  }),
  defineVueRule({
    code: 'vue-setup-props-destructure',
    title: 'setup(props) is destructured',
    problem: 'Destructuring setup(props) creates non-reactive local values.',
    remediation: 'Use props.foo, toRefs(props), or migrate to <script setup> reactive props destructuring.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 1 },
  }),
  defineVueRule({
    code: 'vue-ref-as-operand',
    title: 'Ref used as operand without .value',
    problem: 'Refs used as script operands must be unwrapped with .value.',
    remediation: 'Use .value in script expressions.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 2 },
  }),
  defineVueRule({
    code: 'vue-defineprops-watch-getter',
    title: 'Watch destructured props without a getter',
    problem: 'watch(prop, ...) passes a snapshot value and does not track destructured defineProps bindings.',
    remediation: 'Use watch(() => prop, ...).',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 3 },
  }),
  defineVueRule({
    code: 'vue-watch-require-cleanup',
    title: 'Watcher side effect lacks cleanup',
    problem: 'A watcher creates a long-lived side effect without registering cleanup.',
    remediation: 'Use onWatcherCleanup(), the watcher onCleanup argument, or onScopeDispose().',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 4 },
  }),
  defineVueRule({
    code: 'vue-watch-derived-state',
    title: 'Watcher synchronizes derived state',
    problem: 'A watcher whose only action assigns another ref adds mutable synchronization state and an extra scheduler pass.',
    remediation: 'Replace the target ref and watcher with computed(() => ...).',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 5 },
  }),
  defineVueRule({
    code: 'vue-watch-reactive-property',
    title: 'watch receives a reactive property snapshot',
    problem: 'Passing reactiveObject.property to watch() evaluates the property immediately and is not a reactive source.',
    remediation: 'Pass a getter such as watch(() => state.property, ...).',
    defaultEnabled: true,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 6 },
  }),
  defineVueRule({
    code: 'vue-watch-self-mutation',
    title: 'Watcher mutates its own source',
    problem: 'An unconditional write to the watched ref can retrigger the same watcher and create update loops.',
    remediation: 'Move the mutation to the owning event, derive the value, or add an explicit converging guard.',
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 7 },
  }),
  defineVueRule({
    code: 'vue-watch-async-stale-write',
    title: 'Async watcher can commit stale results',
    problem: 'The watcher writes reactive state after await without invalidating the previous async operation.',
    remediation: 'Use the watcher cleanup callback or onWatcherCleanup() to abort or ignore stale work.',
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 8 },
  }),
  defineVueRule({
    code: 'vue-shallow-ref-nested-mutation',
    title: 'Nested shallowRef mutation is not reactive',
    problem: 'Mutating nested state inside shallowRef does not trigger dependent updates.',
    remediation: 'Replace .value, use ref(), or call triggerRef() after intentional deep mutation.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 9 },
  }),
  defineVueRule({
    code: 'vue-reactive-reassignment',
    title: 'Reactive proxy binding is reassigned',
    problem: 'Replacing a reactive binding disconnects consumers that still hold the original proxy.',
    remediation: 'Mutate proxy properties or use ref() for replaceable state.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 10 },
  }),
  defineVueRule({
    code: 'vue-readonly-mutation',
    title: 'Readonly state is mutated',
    problem: 'Vue ignores mutation through readonly proxies and emits a runtime warning.',
    remediation: 'Mutate state through its owner or expose an explicit update action.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 11 },
  }),
  defineVueRule({
    code: 'vue-shallow-reactive-nested-mutation',
    title: 'Nested shallowReactive mutation is not reactive',
    problem: 'Only root-level shallowReactive properties are reactive; nested mutations do not trigger updates.',
    remediation: 'Replace a root property or use reactive() for deep state.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 12 },
  }),
  defineVueRule({
    code: 'vue-detached-effect-scope-require-stop',
    title: 'Detached effect scope is never stopped',
    problem: 'A detached effectScope keeps captured watchers and computed effects alive until stop() is called.',
    remediation: 'Stop the scope during cleanup or return it to an owner that will stop it.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 13 },
  }),
  defineVueRule({
    code: 'vue-custom-ref-incomplete-contract',
    title: 'customRef tracking contract is incomplete',
    problem: 'A customRef without track() or trigger() does not correctly connect reads and writes to dependents.',
    remediation: 'Call track() from get() and trigger() when set() commits a value.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 14 },
  }),
  defineVueRule({
    code: 'vue-to-refs-plain-object',
    title: 'toRefs receives a plain object',
    problem: 'toRefs expects a reactive object; refs created from a plain object literal are not linked to reactive state.',
    remediation: 'Wrap the object in reactive() first or create individual refs.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 15 },
  }),
  defineVueRule({
    code: 'vue-lifecycle-require-cleanup',
    title: 'Long-lived resource lacks lifecycle cleanup',
    problem: 'The component creates a long-lived browser resource without lifecycle cleanup.',
    remediation: 'Register cleanup with onUnmounted() or onScopeDispose().',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 19 },
  }),
  defineVueRule({
    code: 'vue-watch-require-post-flush',
    title: 'DOM-reading watcher lacks post flush',
    problem: 'A watcher reads DOM state before Vue has flushed owner DOM updates.',
    remediation: 'Pass { flush: \'post\' } or use watchPostEffect().',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 16 },
  }),
  defineVueRule({
    code: 'vue-watch-effect-await-read',
    title: 'watchEffect reads after await',
    problem: 'watchEffect only tracks dependencies read before the first await.',
    remediation: 'Read dependencies before awaiting or use watch() with an explicit source.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 17 },
  }),
  defineVueRule({
    code: 'vue-lifecycle-no-mutation-in-onupdated',
    title: 'Reactive mutation inside onUpdated',
    problem: 'Mutating reactive state in onUpdated can create update loops.',
    remediation: 'Move the reactive mutation to the event or state transition that owns it.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 20 },
  }),
  defineVueRule({
    code: 'vue-prefer-use-template-ref',
    title: 'Prefer useTemplateRef for template refs',
    problem: 'Template refs declared with ref() can drift from the template ref name.',
    remediation: 'Use useTemplateRef(\'name\').',
    sourceBlocks: ['script', 'script-setup'],
    allSourceBlocks: ['template'],
    defaultEnabled: false,
    defaultSeverity: 'info',
    applicability: { vue: { only: 3, minimumMinor: 5 } },
    parseFailureOrder: { script: 21 },
  }),
  defineVueRule({
    code: 'vue-ssr-no-browser-api-in-setup',
    title: 'Browser API used in SSR setup path',
    problem: 'Browser-only APIs are not available during SSR setup.',
    remediation: 'Access browser APIs inside onMounted(), a client-only plugin, or a guarded client branch.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    parseFailureOrder: { script: 22 },
  }),
  defineVueRule({
    code: 'vue-prefer-define-model',
    title: 'Prefer defineModel for v-model props',
    problem: 'Paired prop + update:event declarations can be simplified with defineModel().',
    remediation: 'Use defineModel() or defineModel(\'name\').',
    defaultEnabled: false,
    defaultSeverity: 'warning',
    applicability: { vue: { only: 3, minimumMinor: 4 } },
    parseFailureOrder: { script: 24 },
  }),
  defineVueRule({
    code: 'vue-html-button-has-type',
    title: 'Native button missing type',
    problem: 'A native button defaults to submit inside forms and can trigger accidental form submissions.',
    remediation: 'Add type="button", type="submit", or type="reset".',
    defaultEnabled: false,
    defaultSeverity: 'warning',
    parseFailureOrder: { template: 5 },
  }),
  defineVueRule({
    code: 'vue-onwatcher-cleanup-after-await',
    title: 'onWatcherCleanup called after await',
    problem: 'onWatcherCleanup() must be registered synchronously before the first await in a watcher callback.',
    remediation: 'Move onWatcherCleanup() before the first await in the watcher callback.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3, minimumMinor: 5 } },
    parseFailureOrder: { script: 18 },
  }),
  defineVueRule({
    code: 'vue-ssr-no-random-or-local-time-render',
    title: 'Random or local-time value in SSR render',
    problem: 'Random or local-time values rendered during SSR can differ during hydration.',
    remediation: 'Create stable server state, defer to mounted client code, or isolate with data-allow-mismatch.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    parseFailureOrder: { script: 23 },
  }),
  defineVueRule({
    code: 'vue-model-on-prop',
    title: 'v-model used on a prop binding',
    problem: 'Local prop bindings are not writable, so v-model on a prop cannot work.',
    remediation: 'Use a v-bind binding combined with a v-on listener that emits update:x instead.',
    sourceBlocks: ['script', 'script-setup'],
    allSourceBlocks: ['template'],
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 6 },
  }),
  defineVueRule({
    code: 'vue-model-on-scope-var',
    title: 'v-model used on a template scope variable',
    problem: 'v-for and v-slot scope variables are not writable targets for v-model.',
    remediation: 'Bind a component data/ref property instead of a scoped template variable.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 7 },
  }),
  defineVueRule({
    code: 'vue-template-v-for-key-placement',
    title: 'template v-for key is on a child',
    problem: '<template v-for> keys must be declared on the template tag itself.',
    remediation: 'Move :key to the <template v-for> element.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
    parseFailureOrder: { template: 2 },
  }),
  defineVueRule({
    code: 'vue-if-else-duplicate-key',
    title: 'v-if/v-else branches share a key',
    problem: 'Adjacent v-if / v-else branches must use unique keys.',
    remediation: 'Give each branch a unique :key value.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 8 },
  }),
  defineVueRule({
    code: 'vue-v-bind-sync-removed',
    title: 'v-bind .sync modifier removed',
    problem: 'The .sync modifier was removed in Vue 3.',
    remediation: 'Replace v-bind:arg.sync with v-model:arg.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
    parseFailureOrder: { template: 13 },
  }),
  defineVueRule({
    code: 'vue-v-on-native-removed',
    title: 'v-on .native modifier removed',
    problem: 'The .native modifier is no longer necessary in Vue 3.',
    remediation: 'Remove the .native modifier.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
    parseFailureOrder: { template: 14 },
  }),
  defineVueRule({
    code: 'vue-filters-removed',
    title: 'Vue filters removed',
    problem: 'Filters were removed in Vue 3 and "|" becomes bitwise OR.',
    remediation: 'Use method calls or computed properties instead of filters.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
    parseFailureOrder: { template: 15 },
  }),
  defineVueRule({
    code: 'vue-keepalive-single-child',
    title: 'KeepAlive expects one child',
    problem: '<KeepAlive> expects exactly one child component.',
    remediation: 'Render only one child component inside KeepAlive.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 16 },
  }),
  defineVueRule({
    code: 'vue-invalid-key-nan',
    title: 'Invalid NaN key',
    problem: 'NaN is not a valid VNode key.',
    remediation: 'Use a stable non-NaN key such as a string or number id.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 12 },
  }),
  defineVueRule({
    code: 'vue-async-setup-without-suspense',
    title: 'async setup without Suspense',
    problem: 'async setup() needs a parent Suspense boundary to render.',
    remediation: 'Wrap the component in <Suspense>, or avoid returning a Promise from setup().',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    applicability: { vue: { only: 3 } },
    parseFailureOrder: { script: 25 },
  }),
  defineVueRule({
    code: 'vue-slot-mixed-usage',
    title: 'Mixed slot syntax',
    problem: 'Mixing component children with nested template slots is ambiguous.',
    remediation: 'Use <template #name> for all slots when multiple slots are present.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 17 },
  }),
  defineVueRule({
    code: 'vue-slot-duplicate-name',
    title: 'Duplicate slot name',
    problem: 'Two templates declare the same slot name.',
    remediation: 'Keep a single template for each slot name.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 18 },
  }),
  defineVueRule({
    code: 'vue-vnode-hook-prefix',
    title: 'Deprecated @vnode-* template hooks',
    problem: '@vnode-* hooks in templates are no longer supported after Vue 3.4.',
    remediation: 'Use the vue: prefix instead, for example @vue:mounted.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3, minimumMinor: 4 } },
    parseFailureOrder: { template: 19 },
  }),
  defineVueRule({
    code: 'vue-usemodel-undeclared-prop',
    title: 'useModel on undeclared prop',
    problem: 'useModel() was called with a prop name that is not declared.',
    remediation: 'Declare the prop in defineProps/props, or pass a declared prop name.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3, minimumMinor: 4 } },
    parseFailureOrder: { script: 26 },
  }),
  defineVueRule({
    code: 'vue-usemodel-missing-prop',
    title: 'useModel missing arguments',
    problem: 'useModel() requires props and a declared prop name.',
    remediation: 'Call useModel(props, "propName") with a declared prop.',
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3, minimumMinor: 4 } },
    parseFailureOrder: { script: 27 },
  }),
  defineVueRule({
    code: 'vue-else-without-if',
    title: 'v-else without adjacent v-if',
    problem: 'v-else/v-else-if has no adjacent v-if or v-else-if branch.',
    remediation: 'Place v-else/v-else-if immediately after a v-if or v-else-if branch.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 9 },
  }),
  defineVueRule({
    code: 'vue-if-missing-expression',
    title: 'v-if missing expression',
    problem: 'v-if/v-else-if is missing an expression.',
    remediation: 'Provide a boolean expression for v-if / v-else-if.',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 10 },
  }),
  defineVueRule({
    code: 'vue-for-missing-expression',
    title: 'v-for missing expression',
    problem: 'v-for is missing an expression.',
    remediation: 'Provide a valid v-for expression such as "item in items".',
    defaultEnabled: false,
    defaultSeverity: 'error',
    parseFailureOrder: { template: 11 },
  }),
  defineVueRule({
    code: 'vue-data-allow-mismatch-surgical',
    title: 'data-allow-mismatch needs a reason',
    problem: 'data-allow-mismatch should be a narrow hydration escape hatch with an explicit reason.',
    remediation: 'Add a nearby reason comment or fix the underlying SSR/client divergence.',
    defaultEnabled: true,
    defaultSeverity: 'warning',
    applicability: { vue: { only: 3, minimumMinor: 5 } },
    parseFailureOrder: { template: 20 },
  }),
  defineVueRule({
    code: 'vue-watch-once-unsupported',
    title: 'watch once option is unavailable',
    problem: 'The once option is ignored before Vue 3.4, so the watcher continues running.',
    remediation: 'Upgrade to Vue 3.4+ or stop the watcher explicitly after its first callback.',
    sourceBlocks: ['script', 'script-setup'],
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue-watch-numeric-deep-unsupported',
    title: 'Numeric watch depth is unavailable',
    problem: 'Numeric deep limits require Vue 3.5; older runtimes traverse at full depth.',
    remediation: 'Upgrade to Vue 3.5+ or use a boolean deep option.',
    sourceBlocks: ['script', 'script-setup'],
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'warning',
  }),
  defineVueRule({
    code: 'vue2-reactive-root-unsupported',
    title: 'Vue 2.7 reactive root is unsupported',
    problem: 'Vue 2.7 cannot make root arrays, collections, or primitive values reactive through reactive().',
    remediation: 'Use ref/shallowRef for arrays or a Vue 2 compatible plain-object representation.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 2 } },
  }),
  defineVueRule({
    code: 'vue2-readonly-target-unsupported',
    title: 'Vue 2.7 readonly target is unsupported',
    problem: 'Vue 2.7 cannot construct readonly proxies for arrays, collections, primitives, or frozen objects.',
    remediation: 'Use an extensible plain object or enforce immutability through the owning API.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 2 } },
  }),
  defineVueRule({
    code: 'vue-computed-readonly-write',
    title: 'Readonly computed value is assigned',
    problem: 'A getter-only computed ref rejects writes and retains its derived value.',
    remediation: 'Use computed({ get, set }) or mutate the source state.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue-effect-scope-inactive-run',
    title: 'Stopped effect scope is reused',
    problem: 'effectScope.run() returns undefined after the scope has been stopped.',
    remediation: 'Create a new effect scope instead of reusing a stopped scope.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue-effect-scope-pause-resume-unsupported',
    title: 'Effect scope pause API is unavailable',
    problem: 'effectScope.pause()/resume() requires Vue 3.5.',
    remediation: 'Upgrade to Vue 3.5+ or avoid pausing the scope.',
    sourceBlocks: ['script', 'script-setup'],
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue-watch-handle-pause-resume-unsupported',
    title: 'Watcher pause API is unavailable',
    problem: 'Watcher handles expose pause()/resume() only in Vue 3.5 and newer.',
    remediation: 'Upgrade to Vue 3.5+ or stop and recreate the watcher.',
    sourceBlocks: ['script', 'script-setup'],
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue-async-component-invalid-loader',
    title: 'Async component loader is invalid',
    problem: 'defineAsyncComponent() received a Promise or options without a loader function.',
    remediation: 'Pass a loader function such as () => import("./Component.vue").',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue2-async-component-suspensible',
    title: 'Vue 2.7 ignores async suspensible',
    problem: 'Vue 2.7 async components ignore the suspensible option.',
    remediation: 'Remove suspensible or use Vue 2 async component loading options.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
    applicability: { vue: { only: 2 } },
  }),
  defineVueRule({
    code: 'vue-use-template-ref-duplicate',
    title: 'Template ref key has duplicate bindings',
    problem: 'Multiple useTemplateRef() calls claim the same template ref key.',
    remediation: 'Keep one useTemplateRef binding for each template ref key.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3, minimumMinor: 5 } },
  }),
  defineVueRule({
    code: 'vue-use-template-ref-missing',
    title: 'Template ref key has no element',
    problem: 'useTemplateRef() names a key not declared by any static template ref.',
    remediation: 'Use the exact template ref key or add the missing ref attribute.',
    sourceBlocks: ['script', 'script-setup'],
    allSourceBlocks: ['template'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
    applicability: { vue: { only: 3, minimumMinor: 5 } },
  }),
  defineVueRule({
    code: 'vue-use-template-ref-mutation',
    title: 'Readonly template ref is assigned',
    problem: 'useTemplateRef() returns readonly ref state managed by Vue.',
    remediation: 'Let Vue update the template ref and do not assign its .value.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3, minimumMinor: 5 } },
  }),
  defineVueRule({
    code: 'vue-app-api-misuse',
    title: 'Vue app API lifecycle is invalid',
    problem: 'The app is mounted, configured, registered, or unmounted in an invalid order or shape.',
    remediation: 'Keep app configuration and registrations unique, then mount and unmount once.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
    contextualSeverity: true,
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue-provide-after-setup',
    title: 'Component provide runs after setup',
    problem: 'provide() cannot establish component injection from a mounted lifecycle callback.',
    remediation: 'Call provide() synchronously during setup().',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue2-trigger-ref-invalid-target',
    title: 'Vue 2.7 triggerRef target is invalid',
    problem: 'Vue 2.7 triggerRef() received a value without a triggerable ref dependency.',
    remediation: 'Pass a ref or shallowRef binding.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 2 } },
  }),
  defineVueRule({
    code: 'vue2-async-setup-unsupported',
    title: 'Vue 2.7 async setup is unsupported',
    problem: 'Vue 2.7 does not await a Promise returned by setup().',
    remediation: 'Keep setup synchronous and move async work into lifecycle hooks or explicit actions.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 2 } },
  }),
  defineVueRule({
    code: 'vue-custom-ref-trigger-in-get',
    title: 'customRef getter triggers dependents',
    problem: 'Calling trigger() during customRef get() schedules updates while the value is only being read.',
    remediation: 'Call track() in get() and reserve trigger() for committed setter changes.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
  }),
  defineVueRule({
    code: 'vue2-observer-set-delete-invalid-target',
    title: 'Vue 2 set/delete target is invalid',
    problem: 'Vue 2 observer helpers cannot mutate primitive targets, root data, or array properties with non-index keys.',
    remediation: 'Use a nested reactive object or a non-negative integer array index.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 2 } },
  }),
  defineVueRule({
    code: 'vue-setup-context-expose-misuse',
    title: 'setup context expose is misused',
    problem: 'expose() is called more than once or receives a value that is not an object.',
    remediation: 'Call expose() once with the complete public instance object.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    contextualSeverity: true,
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue-injection-key-invalid',
    title: 'Injection API argument is invalid',
    problem: 'provide()/inject() requires a string or Symbol key and a boolean default-factory flag.',
    remediation: 'Use a string or shared InjectionKey Symbol and a boolean third inject argument.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue-to-raw-long-lived',
    title: 'Raw reactive target escapes',
    problem: 'A toRaw() result is returned and can become a long-lived non-reactive reference.',
    remediation: 'Use toRaw() only for immediate work and do not retain or return the raw object.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
  }),
  defineVueRule({
    code: 'vue-duplicate-provide-key',
    title: 'Injection key is provided twice',
    problem: 'Two provide() calls in the same setup scope overwrite the same key.',
    remediation: 'Provide each key once or merge the value deliberately.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
  }),
  defineVueRule({
    code: 'vue-setup-api-outside-context',
    title: 'Setup API runs without a component instance',
    problem: 'A lifecycle, injection, or instance API is called at regular-script module scope.',
    remediation: 'Move the call into setup() or a composable invoked synchronously by setup().',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue-asset-resolution-outside-context',
    title: 'Asset resolution runs outside render context',
    problem: 'resolveComponent()/resolveDirective() is called without setup or render context.',
    remediation: 'Resolve inside setup/render or import the asset directly.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue-is-shallow-static-false',
    title: 'isShallow branch is unreachable',
    problem: 'isShallow() receives a binding created by a known deep ref/reactive/readonly API.',
    remediation: 'Remove the branch or pass a value that can actually be shallow.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
    applicability: { vue: { only: 3 } },
  }),
  defineVueRule({
    code: 'vue-watch-effect-options-invalid',
    title: 'watchEffect options are ignored',
    problem: 'watchEffect() receives deep, immediate, or once options that only belong to watch().',
    remediation: 'Use watch() when those options are required.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'warning',
  }),
  defineVueRule({
    code: 'vue-api-version-unsupported',
    title: 'Vue API is unavailable in the target version',
    problem: 'Source calls a Vue API introduced after the consuming project runtime.',
    remediation: 'Upgrade Vue to the required minor version or use an older compatible API.',
    sourceBlocks: ['script', 'script-setup'],
    vueVersion: 'known',
    defaultEnabled: true,
    defaultSeverity: 'error',
  }),
  defineVueRule({
    code: 'vue-app-api-version-unsupported',
    title: 'Vue app method is unavailable',
    problem: 'The app instance calls a method introduced after the target Vue 3 minor version.',
    remediation: 'Upgrade Vue to the required minor version or avoid the app method.',
    sourceBlocks: ['script', 'script-setup'],
    defaultEnabled: true,
    defaultSeverity: 'error',
    applicability: { vue: { only: 3 } },
  }),
] satisfies readonly InternalVueRuleDefinition[]

const rulesByCode = new Map(internalVueRuleDefinitions.map((rule) => [rule.code, rule]))

export const vueRuleDefinitions: readonly DoctorRuleDefinition[] = internalVueRuleDefinitions

export function getVueRuleDefinition(code: string): DoctorRuleDefinition | undefined {
  return rulesByCode.get(code)
}

export function resolveVueRuleSeverity(
  code: string,
  contextualSeverity?: DiagnosticSeverity
): DiagnosticSeverity {
  const rule = rulesByCode.get(code)
  const severity = rule?.contextualSeverity && contextualSeverity
    ? contextualSeverity
    : rule?.defaultSeverity
  if (!severity) throw new Error('Vue diagnostic ' + code + ' is not declared in the rule catalog.')
  return severity
}

export function getVueRulesForFailedSourceBlock(kind: SourceBlockKind): readonly DoctorRuleDefinition[] {
  const key = kind === 'template' ? 'template' : 'script'
  return internalVueRuleDefinitions
    .filter((rule) => rule.parseFailureOrder?.[key] !== undefined)
    .sort((left, right) => left.parseFailureOrder![key]! - right.parseFailureOrder![key]!)
}
